<?php
require_once dirname(__FILE__)."/helpers/helper_functions.php";
?>
<!DOCTYPE html>
<html>
<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=1040" />
		<meta name="MobileOptimized" content="1040" />
		<link media="all" rel="stylesheet" href='/css/theme/theme1.css' />
		<link rel="stylesheet" href=<?php echo $this->font_awesome_css_path; ?>/>
		<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700|Roboto:100,300,700" rel="stylesheet">
		<script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
		<style type="text/css">
			.break{
				display: block;
				clear: both;
				page-break-after: always;
			}
		</style>
		<?php echo $tanent_css; ?>
</head>
</head>
<body>
	
	<div class="wrapper">
		<div class="shell">
			<div class="container">
<?php
		//echo 'Hello'.var_dump($this->get('aid'));
		print $this->render($this->sumup_template);
		if($render_subscription_details) {
			
			$this->createSubscriberInvoiceTables($this->lines, $flat_line_types, $usage_line_types, $details_keys);
			print $this->render($this->details_template);
		}
?>
			</div>
		</div>
	</div>
	<script>
		
		var subList = <?php print $this->getSubscribers($this->data->get('aid'));?>;
		console.log(subList);

		$.each(subList, function (i, obj) {
			if(obj.sid != undefined){
				var rowId = "#row_" + obj.sid;
				$(rowId).html(obj.Agensi);
			}
			
		});

	</script>
</body>
</html>
